### ISSUE TITLE
Support passing allowableTags as an array

### ISSUE THREAD

**Issue by ethanresnick** [ericnorris/striptags#1]
Requiring the user to specify their `allowableTags` as a string was unexpected/bizarre when I first encountered it, since the argument's plural name seems to imply that I should provide a list.

That is, I expected to be able to do `striptags(myString, ["p", "li", "ul"])` rather than needing to do `striptags(mystring, "<p><li><ul>")` which, again, is just bizarre.

Also, having to look up the format for the string was a bit annoying.

So I propose allowing the user to specify an array instead, while still supporting the current format. The code change would be really simple—I'd be happy to submit a PR!—and would make things a bit more convenient.

**Comment by ericnorris** [comment]
@ethanresnick thanks for using my npm library! I wrote this as a straight up port of PHP's [strip_tags](https://php.net/strip_tags) into JS, so the allowable_tags parameter is an artifact of that transformation.

I could see how this could be confusing to someone who has not used the PHP version of `strip_tags` though, so I think allowing an array parameter is not a bad idea.

I'll likely have time to change this myself soon, so a PR isn't needed - but thank you for the offer!
