### ISSUE TITLE
Consider registering as a bower package?

### ISSUE THREAD

**Issue by kennyki** [ericnorris/striptags#10]
Hi there, it'd be nice to be able to import this thru bower too.

I see that `striptags` has been taken, may be `striptags.js`?

**Comment by ericnorris** [comment]
Sure why not, I'll close this when I register it. It'd be nice if I could get the name `striptags` as it looks like the original project is 2ish years old and uses regular expressions, which are not safe for stripping HTML.

`striptagsjs` is probably fine though.

**Comment by ericnorris** [comment]
Late update, I released v2.1.2 on http://bower.io - it's not showing up in the search at the moment but `bower info striptagsjs` works.
