### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by kentcdodds** [ericnorris/striptags#14]
Just used it and it worked perfectly. Very intuitive. Thank you!

![warnerarchive-classic-film-key-largo-xTeVhFFa8qB7zP4LXa](https://camo.githubusercontent.com/89f6167f3899be9715d71f0a69bf5706d36c7c31/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7854655668464661387142377a50344c58612f67697068792e676966)

**Comment by ericnorris** [comment]
Haha, no problem. 
:+1:
