### ISSUE TITLE
Option to replace by space?

### ISSUE THREAD

**Issue by JSteunou** [ericnorris/striptags#15]
Would it be possible to add an option to replace closing node by a `&nbps;`? Actually on an example like this `<h1>title</h1><p>Something about nothing.</p>` the result is `titleSomething about nothing.`

**Comment by ericnorris** [comment]
Interesting idea - I'd like to keep this close to the PHP original though. Normally tags are on their own line, so:

``` html
<h1>title</h1>
<p>Something about nothing.</p>
```

would become:

```
title
Something about nothing
```

Is this not the case with your source of HTML?

The [function used inside the state machine](https://github.com/ericnorris/striptags/blob/a901cf3ef4f3d23c8d06a2f1f4b630f313739d4d/striptags.js#L192-L231) to evaluate if a tag is allowed has no notion of opening or closing HTML tags. It is actually executed for every tag it sees in the input. That's actually a part of why the library is so effective, as it is not actually _parsing_ HTML but simply stripping HTML when it sees it.

I could add in the ability to echo out whitespace optionally when a tag is discarded, but the result would be somehing like:

``` html
&nbsp;title&nbsp;&nbsp;Something about nothing.&nbsp;
```

I'm not terribly against the idea, but I'm also not 100% for it. What are your thoughts?

**Comment by JSteunou** [comment]
Actually after reading the state machine code I think it would be difficult
and over enginering. Also it would require to make a difference between
block and inline tag.

**Comment by ericnorris** [comment]
I agree, so I'll go head and close the issue. Thanks for reaching out!

**Comment by jamaica474** [comment]
What about `<br />` tag?
For the following string

`<p> BlaBlabla<br />bla </p>`

I would expect two line out, or at least a space instead of break.

**Comment by ericnorris** [comment]
Hey @jamaica474, looks like this was brought up in #17. As I mentioned above, I wouldn't be opposed to replacing any tag (opening or closing and any type, not just `<br>`) with a space. That is likely what I will end up implementing so hopefully that works for you!
