### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by eawer** [ericnorris/striptags#16]
I'm receiving incorrect output while trying to strip tags from the following string:
`'<p><<< dsadsads</p>'`
Expected output: `'<<< dsadsads'`
Actual output: `''`
Here's the example: https://runkit.com/57db15fae8f17d14002403b9/57dd62a016ccc21400bf4f01

**Comment by ericnorris** [comment]
Hey @Shtirlits, thanks for submitting an issue.

I'd argue that the actual output is correct - the `<<<` is being interpreted as HTML, as they are not HTML encoded. Now if the input was `'<p>&lt;&lt;&lt; dsadsads</p>'`, you'd see the output you'd expect.

You can see that PHP [exhibits the same behavior](https://3v4l.org/IM7Vq) when calling the `strip_tags` function.

**Comment by ericnorris** [comment]
I'm going to go ahead and close this issue, let me know if you have any other questions or concerns. Thanks again!
