### ISSUE TITLE
Replace tags with space

### ISSUE THREAD

**Issue by StephanHoyer** [ericnorris/striptags#17]
If I striptags a string like `foo<br>bar` I get `foobar`. It concats words that should not be concated.

Is there a solution for this? Maybe allow to replace tags with whitespace

https://runkit.com/58344e2e1a87010014709683/58344e2e1a87010014709684

**Comment by ericnorris** [comment]
Oh my, sorry for not responding to this one sooner. I'd like to stick as close as possible to the PHP version, but I am not opposed to this. It seems like it'd be trivial to add. I'll think about it a little bit more over the weekend and maybe get something implemented.

Thanks for your interest!

**Comment by thmsgllghr** [comment]
This module is working great in with export feeds, but I'm also wanting this feature.
Currently, line items are all running together when stripping unordered lists. 
So passing a bool to add space would be greatly appreciated
Thank you.

**Comment by StephanHoyer** [comment]
thanks... Works like a charm!
