### ISSUE TITLE
latin characters?

### ISSUE THREAD

**Issue by sonic182** [ericnorris/striptags#18]
Hi, there is possible to allow characters like '?', 'á', 'é', I haven't found and example (for spanish text)
thanks

**Comment by ericnorris** [comment]
I'm not 100% I understand your question, there is nothing special about non-English characters. All characters are allowed except for HTML characters, which are of course stripped.

See [here](https://runkit.com/585aa67a093c88001389f53f/585aa67a093c88001389f540) for an example. Let me know if I misunderstood!
