### ISSUE TITLE
test if contains HTML

### ISSUE THREAD

**Issue by arisAlexis** [ericnorris/striptags#20]
nice small lib, could be more complete if there was a function to test if a string actually has html tags in it. Just a proposal

**Comment by ericnorris** [comment]
Wouldn't `striptags(maybeContainsHtml) == maybeContainsHtml` prove that a string does not have HTML in it?

**Comment by ericnorris** [comment]
Closing this for now, I think that would be sufficient and doesn't require an update to the library.
