### ISSUE TITLE
Is it possible to also strip br tags?

### ISSUE THREAD

**Issue by vjee** [ericnorris/striptags#22]

**Comment by ericnorris** [comment]
Of course! It strips *all* tags. [Here's an example](https://runkit.com/588814bca141cf0016206a8e/588e87e0c0e737001418c902).

```
let striptags = require("striptags");
let html      = '<br><br><br>meow<br><br><br>';
let output    = striptags(html);

return output;
```
Results in
```
'meow'
```

**Comment by vjee** [comment]
I can't believe i missed that.
Thanks for the quick response
