### ISSUE TITLE
convert argument to string

### ISSUE THREAD

**Issue by kirill-zhirnov** [ericnorris/striptags#23]
Thank you for the great product!

One small issue:

```coffee
stripTags = require 'striptags'
console.log stripTags(890)
```
An empty string will be outputed. To solve it: `console.log(stripTags(String(890)))` - would be nice if it does inside library.

**Comment by ericnorris** [comment]
@kirill-zhirnov thanks for your input! If anything I'd rather throw an error than implicitly convert if given a non-string argument. I'll consider adding that to a future patch version.
