### ISSUE TITLE
Error in UglifyJS with striptags package

### ISSUE THREAD

**Issue by iJoyCode** [ericnorris/striptags#25]
Hello, I've got this error if adding your package as dependency to my project and compile it with webpack 2.2.1 (using UglifyJS).

```
ERROR in standalone.js from UglifyJs
SyntaxError: Unexpected token: name (context) [standalone.js:11814,12]
```
This is a line webpack complain of
```
let context = init_context(allowable_tags, tag_replacement);

**Comment by iJoyCode** [comment]
Looks like it's problem related to uglifyJS, because it doesn't support es6.

**Comment by ericnorris** [comment]
Hey @iJoyCode, sorry about that! You are welcome to use the `2.x.x` branch which is still ES5.

**Comment by jonaswindey** [comment]
Is there a fix planned for this?

**Comment by AndrewLane** [comment]
Any plan to address this?

**Comment by ericnorris** [comment]
@jonaswindey @AndrewLane I'm not sure I follow - you are welcome to continue using the `v2.x.x` branch, which targets ES5.

There are no plans to change the `master` branch to target ES5.

**Comment by AndrewLane** [comment]
Yeah just trying to confirm that you will not be supporting the UglifyJS story in the master branch.
