### ISSUE TITLE
Is the striptags ES6 only compatible?

### ISSUE THREAD

**Issue by tiagostutz** [ericnorris/striptags#26]
Hi!
I'm using striptags with a React Application and when I run the webpack build script it throws errors regarding ES6 'let' and object initialization that is used in striptags.
Do you think it will be useful if we made a script to build a dist version compatible with ES5?

**Comment by ericnorris** [comment]
Hey there @tiagostutz! The latest `3.x.x` versions of striptags are written using minor ES6 features that are generally well supported (`let` and `const`, unless I'm mistaken). These should be supported by all major browsers, but if you still need exactly ES5 support then I'd suggest going with the `2.x.x` branch.

**Comment by tiagostutz** [comment]
Ok! I'll go to 2.x.x branch.
Yeah, the major browsers support indeed, but I think the packagers (like webpack) are still a bit conservative, that's what was happening. In dev mode everthing was OK, but when I ran the build script the problems stucked me.

Thanks a lot!

**Comment by shprink** [comment]
![image](https://user-images.githubusercontent.com/1388706/38615585-7e520b66-3d91-11e8-8b14-8e26485bc073.png)

yes v3 breaks Create React App prod compilation

**Comment by Orinameh** [comment]
Any solution around this? @shprink
