### ISSUE TITLE
v3 breaks uglify

### ISSUE THREAD

**Issue by darobin** [ericnorris/striptags#27]
Version 3 appears to have made the transition to ES6, but does not ship with a transpiled version. Because of that, modules that depend on striptags and get uglified break.

This can be addressed by shipping a transpiled version to npm instead of the source (given the `src` directory, it looks like this may have been the intent?).

If you do not wish to remain compatible with uglify building, it would be useful to at least provide a warning in the docs.

**Comment by ericnorris** [comment]
Hey @darobin! There have already been two issues filed regarding this (#25 and #26). The `2.x.x` branch is still ES5 compatible, and so I'd suggest sticking with that until ES6 support lands in UglifyJS. You can track UglifyJS' ES6 progress in https://github.com/mishoo/UglifyJS2/issues/448.

I don't particularly see a need to ship a compiled ES5 version at the moment, as `let` and `const` are pretty well supported in browsers. I'd rather hold out until the other tooling catches up. A quick search shows that https://github.com/babel/babili appears to be an ES6-ish compatible minifier, so perhaps you could try that?

I'll probably take your suggestion of adding a warning though, to prevent duplicate issues from being filed.

**Comment by darobin** [comment]
Hi! Sorry about that, I somehow screwed up my issues search — must've left it restricted to open issues like a chump.

A warning sounds good — thanks!

**Comment by OronNadiv** [comment]
+1 for adding es5 support in v3 in order not to break UglifyJS. Thanks.

**Comment by dmitrymar** [comment]
In my case IE10 & 11 were throwing an error in my react app. Had to downgrade to 2.2.1.

**Comment by ericnorris** [comment]
@dmitrymar, it should work at least in IE 11. `let` and `const` are both supported according to http://caniuse.com/.

@OronNadiv, there is no functional difference between the core of `v3.0.0` and the `v2.x.x` branch - I have added a streaming mode, but that is likely only useful in a Node context where ES6 is well supported. You're not missing out by sticking with `2.x.x` 😄

**Comment by freiserg** [comment]
Symbol is not supported in IE 11, Edge.
