### ISSUE TITLE
Tag replacement improvement

### ISSUE THREAD

**Issue by JSteunou** [ericnorris/striptags#28]
Would it be possible to make tag_remplacement act different on block or inline tag, or maybe allow tag_replacement to be a function called with current tag returning a string (like `\n` or `&nbsp;`)

**Comment by ericnorris** [comment]
Hey @JSteunou, I really don't feel like that belongs in this library. Understanding inline vs block tags would involve larger changes and make this more of an HTML parser than a tag stripping state machine. We talked about this in #15, and my opinion hasn't changed from then.

**Comment by JSteunou** [comment]
Ahaha I forget I already did bring this topic. But if it comes again it is because it's a strong need.

I totally understand that this lib is not an HTML parser and awareness of tag type is not its job, but, you could delegate the job by accepting `tag_replacement` to be a function returning a String.

No big changes for you, a simple `||` condition [https://github.com/ericnorris/striptags/blob/master/src/striptags.js#L108](here) to use it or call it & use it and it could make some developer happy and save white bears (not sure about that last one though ;) )

**Comment by JSteunou** [comment]
Just pushing a quick example, did not check if it works, but it's so we can see what I meant ;)
