### ISSUE TITLE
"<" and ">" stripped from attribute values

### ISSUE THREAD

**Issue by aspectis** [ericnorris/striptags#30]
In version 2.2.1, the characters `<` and `>` are removed from attribute values of allowed tags:

``` javascript
striptags('<img src="example.jpg" alt="a < b > c">', ['img']);
```

The result should be unaltered, yet `<img src="example.jpg" alt="a b c">` is returned.

Thanks for looking into this.

**Comment by ericnorris** [comment]
If that's the case, then that's a bug in in `v2`! PHP looks like this:
```php
<?php

echo strip_tags('<img src="example.jpg" alt="a < b > c">', '<img>');
```
```html
<img src="example.jpg" alt="a  b  c">
```

[link to php example](https://3v4l.org/SeHit)

I'd rather err to sticking closely to what PHP does, but I'll think about this a bit.

**Comment by aspectis** [comment]
So maybe I will have to file a bug with PHP first :confused:

But I get your point. Thanks for the quick reply, and feel free to close this until PHP gets patched - which I guess won’t happen anytime soon.

BTW, PHP is lying :unamused::

> This function does not modify any attributes on the tags that you allow using allowable_tags [...]. ([PHP manual](http://php.net/manual/en/function.strip-tags.php))
