### ISSUE TITLE
Unexpected token: name (context) when building (Using ES6 `let`)

### ISSUE THREAD

**Issue by foreseaz** [ericnorris/striptags#35]
Error msg as below with UglifyJS, which cannot used on ES6:

```
Failed to compile.
static/js/main.082bd144.js from UglifyJs
Unexpected token: name (context) [./~/striptags/src/striptags.js:17,0][static/js/main.082bd144.js:142975,12]
```

would you consider build src file in ES5?

**Comment by foreseaz** [comment]
Sorry guys, just read the notes:

```
Note: v3+ targets ES6, and is therefore incompatible with the master branch of uglifyjs. You can either:

use babili, which supports ES6
use the harmony branch of uglifyjs
stick with the 2.x.x branch
```

Got it work with version `2.2.1`, keep on the great work and I just close the issue now.

For others get here from Google (including myself, `Read the f* manual` lol

**Comment by ericnorris** [comment]
Ha, no problem @foreseaz. I didn't realize writing an ES6-only NPM library would cause so many issues, but I'd like to keep it ES6 since it's nicer.

**Comment by egoist** [comment]
@ericnorris Would you consider [compiling it to down to ES5](https://github.com/rollup/rollup) as well? However I totally understand that many library authors only publish an ES6 version since they target modern browsers or node.js only.

**Comment by ericnorris** [comment]
@egoist `v2.x.x` is ES5 compatible, and so I'd rather leave that as the go-to for people that need ES5 and have the latest versions be ES6.

**Comment by dancrumb** [comment]
If you have this in your webpack config:

```
rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['es2015'],
            plugins: ['transform-object-rest-spread', 'add-module-exports']
          }
        }
      }
```

Change the `exclude` to `(node_modules(?!\/striptags)|bower_components)`.

That way, babel will compile striptags down for you.
