### ISSUE TITLE
 (IE/uglify) support and removal of global definition of striptags.

### ISSUE THREAD

**Issue by plee-nm** [ericnorris/striptags#38]
I know both of these are  conscious design decisions but I have local fork that removes the need of a polyfill for ES6 support and removes the window.striptags definition on the browser.  These changes would make it easier to support IE 11 and make is safer to bundle up striptags with webpack, browserify etc.  Would you accept a PR with these changes?

**Comment by ericnorris** [comment]
Hey there @plee-nm! I'm not sure I follow why you'd need to remove the global definition of striptags - is writing it in UMD style not enough? I am under the impression webpack and the likes handle that for you automatically when bundling for the browser.

As for the ES5 bit, I'd rather keep this ES6 and let people use the older `v2.x.x` branch if they need ES5. I'd be open to a compelling argument against this, but ES6 is the current version of JS and seems like the right thing to target.

**Comment by plee-nm** [comment]
Hey @ericnorris, thanks for the quick response.  I just added it it with webpack and it seemed to handle the global properly, I have seen it not work with other source code having the exports in it but that must have been the other library's issue.  

I agree that es6 is the way to go, my only change was to remove the Symbol operator.  This would allow for users using Typescript or Babel to have it work properly on IE 11 without a ES6 Symbol or full ES6 shim.  The performance would be negligible and it would allow for most users to stay on the latest version.

**Comment by ericnorris** [comment]
I don't imagine having a shim is a big deal if you're using Typescript or Babel though - what most people are having issues with is `let`, which causes uglify JS to barf.

Am I misunderstanding something here? Or are you saying by getting rid of `Symbol` then people who *don't* use Babel-esque compilers would be able to use the current version of the library? It does look (at a glance) like `Symbol` is the only blocker for IE11 native use.

**Comment by plee-nm** [comment]
@ericnorris  No most people who use babel/Typescript transpile var/let to ES5 but at least in Typescript Symbol needs to be shimmed.   By removing Symbol people using babel/Typescript would be able to your tiny library without including piecemeal shims or a rather large es6 shim.

**Comment by calebeaires** [comment]
I have a similar issue. I have tried to build it on production with angular-cli and it breaks the copilation with this error

```
ERROR in vendor.41c05958110e9f9072d3.bundle.js from UglifyJs
Unexpected token: name (context) [vendor.41c05958110e9f9072d3.bundle.js:207991,12]
```

**Comment by ericnorris** [comment]
@plee-nm I've updated `striptags` to support IE11 by having a tiny `Symbol` polyfill (and refraining from using a couple ES6 features). The commit is 9ed9eb07fbae46aca20f397dc9181f3feb87432c.
