### ISSUE TITLE
Shouldn't script code string wrapped in 'script' tag be stripped?

### ISSUE THREAD

**Issue by asionius** [ericnorris/striptags#40]
test string:
'<script>alert("this is a script")</script>'
output:
alert("this is a script")
Result I expect is ""

**Comment by ericnorris** [comment]
Hey @asionius! `striptags` does not remove the content of tags, only the tags themselves. In the example you gave, you would get `alert("this is a script")`, but that would be rendered as actual text in a browser.

**Comment by asionius** [comment]
@ericnorris thanks for your attention. 
I have figured out striptags worked in that way.
Yes result would be rendered as actual text in browser. If striptags offer an option to enable auto identify tags which should be stripped only themselves or be removed all containing the content. And strip tags in that way. For example, tag ‘style’ should be removed containing content while tag ‘p’ or tag ‘div’ should be removed only themselves. That would be nice.
