### ISSUE TITLE
striptags in version 3.0.0 and 3.1.0 wouldn't compile with uglify-es

### ISSUE THREAD

**Issue by apepper** [ericnorris/striptags#42]
If you try to compile `striptags` version `3.0.0` or `3.1.0` using `uglify-es`, it will fail with a cryptic message:

```
ERROR in index.js from UglifyJs
Unexpected token: name (n) [index.js:1,863]
```

If I downgrade to `striptags` version `2.x`the problem disappears. I'm not sure if this is a `striptags` bug, or one of the other involved packages like `webpack`, `babel-core`, `uglifyjs-webpack-plugin`, or `uglify-es`.

### How to reproduce

I prepared a minimal example how to reproduce this: https://gist.github.com/apepper/d149caadacea6852623ff42325829469

* Place all files of that gist in a folder. Please note, that a beta version of `uglifyjs-webpack-plugin` is used, which already relies on `uglify-es` instead of `uglify-js`.
* File `src_index.js` needs to be in `src/index.js`, but github will not let me use / in file names.
* run `npm install` in terminal
* run `npm run build` in terminal

### Expected

The build should finish successfully.

**Comment by ericnorris** [comment]
Hey @apepper! The README specifies that v3+ is not compatible with the `master` branch of `uglify-js`.

> Note: v3+ targets ES6, and is therefore incompatible with the master branch of uglifyjs. You can either:
>
> * use babili, which supports ES6
> * use the harmony branch of uglifyjs
> * stick with the 2.x.x branch

**Comment by apepper** [comment]
@ericnorris I'm completly aware of the readme section. That is why, I use `uglify-es` instead of `uglify-js`. Accodring to https://www.npmjs.com/package/uglify-es :

> ### uglify-es
> A JavaScript parser, mangler/compressor and beautifier toolkit for ES6+.

So it should work with ES6.

Again I'm not 100% sure, if this is a `striptags` issue or one of the other involved packages like `webpack`, `babel-core`, `uglifyjs-webpack-plugin`, or `uglify-es`.

Please reconsider option this issue again.

**Comment by apepper** [comment]
I found a workaround. If you follow instructions of https://github.com/facebookincubator/create-react-app/issues/1125#issuecomment-267920849 it is possible to tell `babel-loader` to transpile node modules, if you explicitly add them in the `include` rule.
