### ISSUE TITLE
Remove tag from a json object

### ISSUE THREAD

**Issue by natan88** [ericnorris/striptags#43]
I have an object like this:
`let obj = {
text: '<font color=\"#ff3300\">red</font>',
name: 'My name is <b>natan</b>'
}`

Call striptags (obj) returns empty. I wanted it to return:

`{
text: 'red',
name: 'My name is natan'
}`

Is there any way to use json objects?

**Comment by ericnorris** [comment]
Hey @natan88, if you wanted to strip HTML from values in JSON, I would suggest calling it on the individual values, not the object itself. Something like (not tested):

```
var stripped_object = {};

for (var key in obj) {
  stripped_object[key] = striptags(obj[key]);
}
```
