### ISSUE TITLE
[Old Chromes] Uncaught SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by felipefialho** [ericnorris/striptags#48]
I am using Angular in my application. 
After build, it doesn't work on old Chromes and I've been received the follows message on console.

![screen shot 2018-03-14 at 11 07 03 am](https://user-images.githubusercontent.com/3603793/37407293-0ec5c848-2778-11e8-9430-d6c72e52da87.png)

Checking it... the problem is this code

```
const STATE_PLAINTEXT = Symbol('plaintext');
const STATE_HTML      = Symbol('html');
const STATE_COMMENT   = Symbol('comment');

const ALLOWED_TAGS_REGEX  = /<(\w*)>/g;
const NORMALIZE_TAG_REGEX = /<\/?([^\s\/>]+)/;
```

After transpile I get.

```
const l=o("plaintext"),a=o("html"),u=o("comment"),s=/<(\w*)>/g,c=/<\/?([^\s\/>]+)/;
```

Do you have any idea?

**Comment by ericnorris** [comment]
Hey @LFeh! If you are targeting older versions of Chrome that do not support `const`, I would suggest you either a) ensure your JS compiler targets an earlier version of ECMAScript or b) use the `2.x.x` branch of `striptags`.
