### ISSUE TITLE
Substitution error

### ISSUE THREAD

**Issue by thiagorova** [ericnorris/striptags#51]
Hi,
first of all, thanks a lot, this package is pretty cool.
I found something that is, apparently, an error.

on the docs, it is saying that:

```
ex = '<a href="https://example.com">' +
        'lorem ipsum <strong>dolor</strong> <em>sit</em> amet' +
    '</a>'
"<a href="https://example.com">lorem ipsum <strong>dolor</strong> <em>sit</em> amet</a>"
stripTags(ex, [], '\n');
```
would yield:
```
lorem ipsum
dolor
 sit amet
```

The result, though, is this:
```
lorem ipsum 
dolor
 
sit
 amet
```

basically, if I'm not seeing anything weirdly, the problem is that striptags is substituting both the opening and the closing tag...

**Comment by ericnorris** [comment]
You are correct! That is expected, although the documentation being wrong is not :)

I'll update the README. Thanks!
