### ISSUE TITLE
"striptags" leaves whitespace and line breaks.

### ISSUE THREAD

**Issue by nazarposhta** [ericnorris/striptags#53]
HI. I'm trying to use "striptags" for stripping HTML code where are `ul li` `ol li` elements. And as a result I get text with whitespace and line breaks in places where these tags were. 
My source looks like this: 
```
<p><strong>bold</strong> <em>italic</em> <u>underline</u> <del>stripe</del>&nbsp;</p>
<ol>
  <li>bullet</li>
</ol>
<ul>
  <li>numlist</li>
</ul>
<p><a href="https://github.com/ericnorris/striptags">link</a></p>
```
after decoding to HTML by [https://www.npmjs.com/package/decode-html](url) it looks like this:
```
<p><strong>bold</strong> <em>italic</em> <u>underline</u> <del>stripe</del> </p>
<ol>
  <li>bullet</li>
</ol>
<ul>
  <li>numlist</li>
</ul>
<p><a href="https://github.com/ericnorris/striptags">link</a></p>
```
then after using "striptags" with only one parameter HTML, I get:
```
bold italic underline stripe 

  bullet


  numlist

link
```

**Comment by ericnorris** [comment]
Hey @nazarposhta! That is correct, the whitespace that was previously in the document is left unchanged, this library only removes tags. If you'd like to remove the extra whitespace, you will need to do some text parsing - perhaps a regex to remove duplicate spaces?

I'm closing this out as it is not actually a bug, but thank you for your interest.
