### ISSUE TITLE
Not Removing &nbsp tag

### ISSUE THREAD

**Issue by roshanyadav810** [ericnorris/striptags#55]
I am removing all html tags for this string "<p> <img alt=\"2\" src=\"https://ae01.alicdn.com/kf/HTB142nSax2rK1RkSnhJq6ykdpXaQ.jpg\"> <img alt=\"3\" src=\"https://ae01.alicdn.com/kf/HTB1uvrSax2rK1RkSnhJq6ykdpXaf.jpg\"> <img alt=\"4\" src=\"https://ae01.alicdn.com/kf/HTB1MLDRaDjxK1Rjy0Fnq6yBaFXay.jpg\"> <img alt=\"5\" src=\"https://ae01.alicdn.com/kf/HTB1OGzSayYrK1Rjy0Fdq6ACvVXal.jpg\"> <img alt=\"6\" src=\"https://ae01.alicdn.com/kf/HTB1Ts6NasfrK1Rjy0Fmq6xhEXXaQ.jpg\"> <img alt=\"7\" src=\"https://ae01.alicdn.com/kf/HTB1b4LUatfvK1RjSszhq6AcGFXaW.jpg\">  &nbsp;<.."
through striptags.
but it's returning no breaking space tag"&nbsp;". Please look into this. Thanks

**Comment by ericnorris** [comment]
Hey @roshanyadav810! `striptags` removes HTML tags, not HTML entities.
