### ISSUE TITLE
html entities?

### ISSUE THREAD

**Issue by dcsan** [ericnorris/striptags#56]
can you add an option to remove things like `&nbsp` ?

**Comment by niftylettuce** [comment]
You could probably just use `he`'s method `he.decode(html)` to do this:

https://www.npmjs.com/package/he#hedecodehtml-options

```js
striptags(he.decode(html))
```

Mark resolved if this is OK?

**Comment by danawoodman** [comment]
Bumpppp

**Comment by ericnorris** [comment]
Hey! Didn't realize I had missed this - I am not planning on making any changes to this library that fall outside of the basic behavior of PHP's [strip_tags](https://www.php.net/manual/en/function.strip-tags.php) function, which this library is based on.
