### ISSUE TITLE
Remove empty tags

### ISSUE THREAD

**Issue by decebal** [ericnorris/striptags#57]
After stripping the tags some of them remain empty, would be nice to have a feature for removing the empty tags or just have it enabled by default.

Example:
Given:
```js
// const synopsis=
<p><a href="#">Link to same page</a></p>
```

```js 
striptags(synopsis, ['p', 'ul', 'li', 'ol', 'div', 'strong', 'span', 'i'])
```

should just return empty string, instead it returns `<p></p>`

**Comment by ericnorris** [comment]
Hey @decebal! `striptags` is not an HTML parsing library, and it has no semantic understanding of the actual HTML - it only claims to strip anything that could be potentially interpreted as a tag by the browser. If you want something to handle this, I'd suggest looking into a library that can parse HTML.

Also, unless I'm missing something your example would not have an empty `<p>`:

```
var striptags = require("striptags")

var synopsis = '<p><a href="#">Link to same page</a></p>'

// prints "<p>Link to same page</p>"
striptags(synopsis, ['p', 'ul', 'li', 'ol', 'div', 'strong', 'span', 'i'])
```
