### ISSUE TITLE
Heart emoji is stripped

### ISSUE THREAD

**Issue by EddieOne** [ericnorris/striptags#6]
<3

**Comment by ericnorris** [comment]
Hey @EddieOne, do you mean the literal string "<3" is stripped when using striptags? If so, that is by design - if you don't want the < character stripped then you should pass it as an HTML encoded string to the function.

For example:

```
striptags('<span>&lt;3<span>')
```

produces:

```
'&lt;3'
```

...which you can then decode back into <3.

**Comment by EddieOne** [comment]
ok thanks
