### ISSUE TITLE
[question] Handling opening and closing tags differently

### ISSUE THREAD

**Issue by guillaumegarcia13** [ericnorris/striptags#63]
Let's assume that we want to leverage the `tagReplacementText` of the [Advanced Usage](https://github.com/ericnorris/striptags#advanced-usage).

1. Would it be possible to have the replacement for?
-  both tags (opening and closing)
-  opening tag only
-  closing tag only

A quick example: let-s say I want to convert my HTML string to markdown
```
<li>item 1</li>
<li>item 2</li>
```

should become (only opening tag)
```
* item 1
* item 2
```

------------------------------------------------------------------------------

2. More challenging, how would you process nested lists:
```
<ul>
    <li>item 1
        <ul>
            <li>item 1.1</li>
        </ul>
    </li>   
    <li>item 2</li>
</ul>
```

that should be represented like this:
```(markdown)
* item 1
    * item 1.1
* item 2
```

but I'm unsure whether this can be achieved without parsing capabilities 🤔 which I understood you discarded to stick closely to the original PHP function, right? 

Thanks for your insights! 🙏🏻

**Comment by sebmos** [comment]
I'm not the developer of this package, so take what I'm saying with a grain of salt - but I think you're looking in the wrong place, for the following reasons:

In general, it looks like you're trying to parse HTML into Markdown. I would look among the many Markdown packages for that behaviour, if it exists. (I'm not sure it does - it's easy enough to parse `<li>` and `<b>`, but how would you deal with complex HTML that does not simplify down to Markdown?)

The second request doesn't actually make any sense. The HTML code you posted does not result in a nested list item 1.1, so even if you were parsing this HTML into Markdown, you wouldn't end up with a nested list. I would be very careful in using spacing in a way that HTML doesn't intend it to be used as - you'll just end up in a world of hurt! :-)

**Comment by guillaumegarcia13** [comment]
Hi,

Thanks, I corrected the (faulty) snippet.
Meanwhile, I turned to [unifiedjs](https://github.com/unifiedjs/unified) and wrote a compiler.
