### ISSUE TITLE
GitHub Security Lab: Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [ericnorris/striptags#67]
Hello,

The GitHub Security Lab team has found a potential vulnerability in your project. Please create a Security Advisory and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a Security Policy containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to GHSL-2021-074.

Thank you,
Agustin Gianni
GitHub Security Lab

**Comment by ericnorris** [comment]
This has been addressed in https://github.com/ericnorris/striptags/commit/f252a6b0819499cd65403707ebaf5cc925f2faca, and published here: https://github.com/ericnorris/striptags/security/advisories/GHSA-qxg5-2qff-p49r.
