### ISSUE TITLE
striptags(undefined) causes a TypeError

### ISSUE THREAD

**Issue by accessdev** [ericnorris/striptags#7]
this is a difference between this implementation and the PHP implementation.

var_dump(strip_tags(null));

> string(0) ""

striptags(undefined);

> TypeError: Cannot read property 'length' of undefined
>     at striptags (\dir\node_modules\striptags\src\striptags.js:27:30)
>     at repl:1:11
>     at REPLServer.defaultEval (repl.js:132:27)
>     at bound (domain.js:254:14)
>     at REPLServer.runBound [as eval](domain.js:267:12)
>     at REPLServer.<anonymous> (repl.js:279:12)
>     at REPLServer.emit (events.js:107:17)
>     at REPLServer.Interface._onLine (readline.js:214:10)
>     at REPLServer.Interface._line (readline.js:553:8)
>     at REPLServer.Interface._ttyWrite (readline.js:830:14)

Could you check that html has a length property because accessing it ?

Thanks !

**Comment by ericnorris** [comment]
Hey there @accessdev, sure thing. I'll close this once I push it out.
