### ISSUE TITLE
striptags not removing inner tags.

### ISSUE THREAD

**Issue by DeveloperAdd007** [ericnorris/striptags#71]
Lets say i want to allow `P` tag but not `B` tag but if i put `B` tag inside `P` then it's not removing a tag.

Content: `<p>ashish <b>asdasd</b></p>`

Code: striptags(pastedText, `<p>`)

OutPut: `<p>ashish <b>asdasd</b></p>`

Is there any way where i can remove inner tag as well?

**Comment by ericnorris** [comment]
Hello @DeveloperAdd007, what version are you using? I am unable to replicate the behavior you're seeing in both `3.2.0` and the `4.0.0-alpha2`:

- `3.2.0`: https://runkit.com/embed/v52yqeck7cs3
- `4.0.0-alpha2`: https://runkit.com/embed/bdw28eiolg0c

Both result in:

```
<p>ashish asdasd</p>
```

...which is expected as far as I'm aware. Keep in mind that if you want more advanced tag stripping functionality, you should be using an HTML parser, not this library.
