### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Volkodaf** [ericnorris/striptags#78]
Hello! 
When i'm try to import your package with `import striptags from striptags;` node.js throws next errors: 
- `striptags can be imported only by using import striptags = require(striptags)`
- `(0 , striptags_1.default) is not a function`

Node.js version 16.18.0
Striptags version 3.2.0

Could you please fix this?

**Comment by ericnorris** [comment]
If you'd like to `import striptags`, you can use the latest `v4` alpha release. Otherwise, I believe you'll need to use `require`, as the error message says.

I'm not planning on making any updates to `v3`.
