### ISSUE TITLE
`<` without matching `>` removes all text after it

### ISSUE THREAD

**Issue by AbleLincoln** [ericnorris/striptags#79]
For example:
`4 is <5 right?` will give `4 is `

Is this intentional?

**Comment by ericnorris** [comment]
Yes, because that string has a tag called `5`. Theoretically, someone could write `<5 onfocus=alert("xss")>`, or cause `onfocus=alert("xss")`  to be appended to the string `<5`, so it's safest to remove all tags, even if they're unfinished.
